### ISSUE TITLE
Good😍

### ISSUE THREAD

**Issue by jamalnggau1** [Nikollya/python#1]
make like this👉 https://github.com/Alexsey272/Anon-Plaid
https://github.com/Tokimaro/Anonim_tg_bot
https://github.com/gigstate/tg-chat-bot
it will be really good

**Comment by Nikollya** [comment]
Thanks for this
Спасибо за это!


чт, 25 нояб. 2021 г., 19:07 Jamal nggau ***@***.***>:

**Comment by jamalnggau1** [comment]
you're welcome. I'm waiting for the update. The 3 codes have their respective shortcomings, I hope you can complete them in your code

**Comment by Nikollya** [comment]
https://github.com/gigstate/tg-chat-bot/issues/5

**Comment by jamalnggau1** [comment]
try this one https://github.com/Alexsey272/Anon-Plaid he is always online and answers questions! she is so amazing

**Comment by jamalnggau1** [comment]
https://github.com/Tokimaro/Anonim_tg_bot
I've tried this but can't send pictures. I've tried adding but failed
